### ISSUE TITLE
When using bb() and data() at the same time, "this" is undefined in data

### ISSUE THREAD

**Issue by teuneboon** [mikeapr4/vue-backbone#4]
Now I know this is likely not gonna be fixed, and we're currently working around this anyway, but I thought I'd at least document this issue in case others run into it:

Normally in vue components you can do something like this:

```
props: ['foobar'],
data() {
    console.debug(this); // returns the component
    return {
        foo: this.foobar,
    }
}
```

If you use bb() in the same component however, `this` will be undefined in the data() method. So something like this won't work:

```
props: ['foobar'],
bb() {
    return {
        nice_collection: new NiceCollection(),
    };
},
data() {
    console.debug(this); // returns "undefined"
    return {
        foo: this.foobar,
    };
}
```

Hope this prevents some people from wondering why their code won't work for half a day like me :)

**Comment by mikeapr4** [comment]
hey @teuneboon, sorry to hear this issue cost you time. I've looked over the code, at first glance it looks easily fixable. I'm gonna run some regression tests and make sure it is ok, if for some reason this can't be fixed, at a minimum I'll update the docs to call it out.

**Comment by mikeapr4** [comment]
hey @teuneboon, try out **v0.1.3** - any problems, let me know :+1:

**Comment by teuneboon** [comment]
@mikeapr4 Works great so far, thanks! Appreciate you taking the time for a couple of years old project to fix this issue. Closing issue as this is fixed now.
